version: "3.4"

services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8089:8080"    # HTTP端口映射
      - "50055:50051"  # gRPC端口映射
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      AUTHENTICATION_APIKEY_ENABLED: "false"
      AUTHENTICATION_OIDC_ENABLED: "false"
      AUTHORIZATION_ADMINLIST_ENABLED: "false"
      DEFAULT_VECTORIZER_MODULE: "none"
      ENABLE_MODULES: ""
      QUERY_DEFAULTS_LIMIT: "25"
      # 单节点配置
      CLUSTER_HOSTNAME: "node1"
      ENABLE_CRON: "false"
      # 禁用集群模式
      ENABLE_CLUSTER: "false"

  console:
    image: semitechnologies/weaviate-console
    container_name: weaviate-console
    ports:
      - "3000:80"
    environment:
      WCS_CONSOLE_WEAVIATE_URL: "http://weaviate:8080"
    depends_on:
      - weaviate

volumes:
  weaviate_data: 