# Weaviate向量数据库配置
database:
  weaviate:
    host: "localhost"      # Docker主机地址
    port: 8089            # Docker映射的HTTP端口
    grpc_host: "localhost" # Docker主机地址
    grpc_port: 50055      # Docker映射的gRPC端口
    scheme: "http"         # 协议类型
    api_key: null          # Docker配置中禁用了API key
    timeout: [5, 30]       # 连接超时设置

# 分片配置
fragmentation:
  enable: true                    # 是否启用分片功能
  max_chunk_size: 500           # 最大chunk大小
  min_fragment_size: 100         # 最小分片大小
  chunk_overlap: 50             # 分片重叠大小
  enable_context_rebuild: true   # 是否重构上下文

# 其他配置可以根据需要添加
# embedding:
#   model: "text-embedding-ada-002"
#   api_key: "your-api-key"

# llm:
#   provider: "openai"
#   model: "gpt-3.5-turbo"
#   api_key: "your-api-key" 

# 图片处理配置
image_processing:
  enabled: true
  storage_path: "storage/images"
  vision_model: "glm-4v-plus"
  api_key: "${ZHIPUAI_API_KEY}"
  context_window: 3
  max_concurrent: 5
  timeout: 30
  retry_count: 3
  cache_enabled: true
  cache_ttl: 3600